application: demaratus-dyn
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: "2.6"

handlers:
- url: /static/ace
  static_dir: ace-builds/src-noconflict
- url: /.*
  script: demaratus.application
  secure: always

inbound_services:
- channel_presence

